---
- name: add user
  user: 
    name: {{ username }}
    shell: /bin/bash
    state: present
    password: '{{ passwd_hash }}'
- name: create authorized_keys
  authorized_key: 
    user: {{ username }}
    state: present
    key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
- name: add master public key to authorized_keys
  shell: /bin/echo {{ public_key }} >> /home/{{ username }}/.ssh/authorized_keys
#- name: set sudoer
#  lineinfile: 
#    path: /etc/sudoers
#    state: present
#    line: '{{ username }}  ALL=(ALL)       ALL'
#- name: alter sshd_config
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#    state: present
#  with_items:
#    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
#    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
#    - { regexp: "^Port", line: "Port 22" }
#- name: restart sshd
#  service: name=sshd state=restarted
##used vars: username passwd_hash public_key
